### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by alekseevaiana** [UseKeyp/kaching-app#22]
### Tasks
- [x] Check if all icons have the right colors
- [x] Check that fonts are correct and showing
- [x] Decide what user will see if they goes to the root page "/"
- [x] Make sure that scrolls are working correct on every page
- [x] Amount selection should include the token name at all times, even during user input 
![image](https://github.com/UseKeyp/kaching-app/assets/35622595/3f05150e-fc17-422e-98f7-10d579adf69d)

**Comment by alekseevaiana** [comment]
## Additional
- Input should save value after second changing
- Show "where to send" under recipient
- Make button with green bg on SendForm page if form is valid

**Comment by alekseevaiana** [comment]
<img width="386" alt="Screenshot 2023-06-16 at 11 25 23 AM" src="https://github.com/UseKeyp/kaching-app/assets/36742189/f8360ba3-9095-446e-9b2d-2b6e6515d57c">

Discuss with Sasha and Patrick how to prevent multiple transactions accidentally.

**Comment by alekseevaiana** [comment]
Leave fonts for QA meeting with Sasha
